//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusquedaDeParejas.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class generico {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal generico() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusquedaDeParejas.Idiomas.generico", typeof(generico).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        internal static string BtnContinuar {
            get {
                return ResourceManager.GetString("BtnContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificultad.
        /// </summary>
        internal static string BtnDificultad {
            get {
                return ResourceManager.GetString("BtnDificultad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string BtnIdioma {
            get {
                return ResourceManager.GetString("BtnIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string BtnIniciar {
            get {
                return ResourceManager.GetString("BtnIniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clasificacion.
        /// </summary>
        internal static string BtnRanking {
            get {
                return ResourceManager.GetString("BtnRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string BtnSalir {
            get {
                return ResourceManager.GetString("BtnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu.
        /// </summary>
        internal static string BtnSalirJuego {
            get {
                return ResourceManager.GetString("BtnSalirJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string button2 {
            get {
                return ResourceManager.GetString("button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GANASTE!!!.
        /// </summary>
        internal static string ganador1 {
            get {
                return ResourceManager.GetString("ganador1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busqueda de Parejas.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce tu nick:.
        /// </summary>
        internal static string label12 {
            get {
                return ResourceManager.GetString("label12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PERDISTE!!!.
        /// </summary>
        internal static string LblPerdiste {
            get {
                return ResourceManager.GetString("LblPerdiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reintentar.
        /// </summary>
        internal static string Reintentar {
            get {
                return ResourceManager.GetString("Reintentar", resourceCulture);
            }
        }
    }
}
